### ISSUE TITLE
Colab Example

### ISSUE THREAD

**Issue by AmitMY** [browsermt/bergamot-translator#207] opened 2021-07-28 07:50 UTC
I think this project is lovely, but I was wondering if you could make it a tiny bit more accessible by creating an example on colab?

Specifically:
1. Install Dependencies
2. Process data
3. Train model
4. Convert to wasm / any other client-side requirements

Thanks!

**Comment by kpu** [comment] 2021-07-28 08:38
We're working on automating in https://github.com/mozilla/firefox-translations-training .  High-resource models take multiple weeks worth of GPU time to train (we usually use 8-GPU machines) so Colab would be limited to toys or languages with tiny training data.  My target is therefore slurm clusters.

**Comment by AmitMY** [comment] 2021-07-28 09:23
Thanks, I understand.
I still think that a toy example in colab would make this project more accessible.

It would be clear, at a glance, how it works, and what it requires.

I agree that it's not optimal, definitely not for large models in high resource languages, but still is valuable.

**Comment by jerinphilip** [comment] 2022-01-27 01:18
Please find [this notebook on colab](https://colab.research.google.com/drive/1AHpgewVJBFaupwAbZq0e6TdX6REx0Ul0?usp=sharing), which is the demonstration of a python package provided from here. The command line is an entry point provided through python using the library, which we expect to refine eventually. 

The python package focuses on inference using already prepared models. Please remember that this colab/python attempt is an effort outside the official deliverables of the [Bergamot Project](https://browser.mt). Nevertheless, we will try to keep documentation available: https://browser.mt/docs/main/python.html.

As for the other part of the request - a complete example from setup to data to training to model packaging, our understanding is that Colab is not well-suited for the case given the ecosystem (which is not entirely python). However, https://github.com/mozilla/firefox-translations-training has since added Singularity (docker for where you don't have root, e.g., SLURM clusters managed by someone else), which should help reproducibility.

Closing this issue.

**Closed by jerinphilip** 2022-01-27 01:18 UTC
