### ISSUE TITLE
Build fails for some users when using the Docker build setup in the wasm-integration branch

### ISSUE THREAD

**Issue by motin** [browsermt/bergamot-translator#31] opened 2021-02-17 18:16 UTC
Re-filing this here: https://github.com/mozilla-extensions/bergamot-browser-extension/issues/28

**Comment by abhi-agg** [comment] 2021-02-18 11:08
We found that the build failures were not reproducible for a fresh clone of the [extension](https://github.com/mozilla-extensions/bergamot-browser-extension/tree/clarify-bergamot-translator-build-dependency). As it wasn't an issue specific to this repo, I am closing it.

**Comment by motin** [comment] 2021-02-18 13:00
This particular error was a failure to build bergamot-translator using the Docker setup in the wasm-integration branch. Let's keep the issue open until we have removed the Docker build setup.

**Closed** 2021-02-18 13:04 UTC

**Comment by eu9ene** [comment] 2021-02-19 23:08
hey @motin @abhi-agg, I have the opposite problem. I was able to build using docker and make file easily, but can't build locally because of some problems with the local environment (permissions specifically). Usually, docker based builds are way more reproducible. Based on what you decided that it is not reproducible?

**Comment by motin** [comment] 2021-02-20 16:35
My too @eu9ene. Created a new issue with more context included, so that we can discuss this :) https://github.com/mozilla/bergamot-translator/issues/4
